apiVersion: apps/v1
kind: Deployment
metadata:
  name: net5-deployment-116
  labels:
    app: net53
    env: testing1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: net5-116
      env: testing-116
  template:
    metadata:
      labels:
        app: net5-116
        env: testing-116
    spec:
      containers:
      - name: net5
        image: 192.168.3.224/zhaoxi/net5-4.0:latest
        ports:
        - name: http-port
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: net-project
  labels:
    app: net-project
    env: testing
spec:
  selector:
    app: net5-116
    env: testing-116
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30050
  type: NodePort